services:
  boilerplate:
    build:
      context: .
      target: final
    environment:
     - LEVEL 
    volumes:
      - ./testcases:/usr/src/app/testcases
      - ./src:/usr/src/app/src
      - ./output:/usr/src/app/output