services:
  boilerplate:
    image: ${CONTAINER_NAME}
    container_name: temp_${CONTAINER_NAME}
    build:
      context: .
      target: final
    environment:
     - LEVEL 
    volumes:
      - ./testcases:/usr/src/app/testcases
      # - ./src:/usr/src/app/src
      - ./output:/usr/src/app/output